### ISSUE TITLE
App does not close properly in v11

### ISSUE THREAD

**Issue by namigop** [AvaloniaUI/Avalonia.Controls.TreeDataGrid#195] opened 2023-07-20 01:48 UTC
**Steps to recreate**

1. Compile and Run the TreeDataGridDemo
2. Click on the Close button (upper left) 

**Expected** : App should close
**Actual** : "Spinning wheel" (i'm on a mac) is shown and app does not close

Note: I have another app which had a TreeDataGrid v0.10.x and there I don't see this issue

**Comment by maxkatz6** [comment] 2023-07-20 02:20
Duplicate of https://github.com/AvaloniaUI/Avalonia/issues/11159

**Closed by maxkatz6** 2023-07-20 02:20 UTC
